### ISSUE TITLE
Latex equations are not always rendered 

### ISSUE THREAD

**Issue by tmalsburg** [eschulte/epresent#17]
Latex equations are often (but not always) not displayed in their rendered form. To fix that I added (org-preview-latex-fragment) at the end of epresent-next-page and epresent-previous-page. However, when I execute a code block on the same slide, the rendered equation is replaced by the LaTeX source so this hack doesn't really solve it.

**Comment by tmalsburg** [comment]
I found the following: if the cursor is placed before the first slide when I start the presentation, the formulae are rendered correctly.  However, if the cursor is placed anywhere later than that (i.e. on the first slide or later), their source is displayed.

**Comment by eschulte** [comment]
This should be fixed in the recent commit from tmalsburg.  Please re-open if the problem persists.
