### ISSUE TITLE
Display code with different background color

### ISSUE THREAD

**Issue by mauro3** [eschulte/epresent#27]
It is sometimes quite hard to discern which bits are code which not.  Can the code be underlain with a different background color? If so how.

An example would be the grey background to this code:
```python
def f(x):
    x+x
```

**Comment by eschulte** [comment]
If you can do this in Org-mode, then you should be able to do it in epresent.el (with appropriate setup and teardown when epresent starts and exits).  It looks like the following worg page has instructions.  http://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html

**Comment by mauro3** [comment]
Thanks for the link.  I had a color-theme which colored the code-blocks but that didn't come through in epresent.  Now I'm using a different theme with above trick and that works.
