### ISSUE TITLE
Go to the nth slide

### ISSUE THREAD

**Issue by shakthimaan** [eschulte/epresent#28]
#1 When I quit the presentation to show a demo, and want to resume from the nth slide, I have to press 't' followed by 'n' (n times).

Is it possible to write a function to directly move to the nth slide?

#2 It will be good to have an option to show the title, author, date on all the slides (as a footer) along with the slide count. For example: [3/10].

**Comment by sellout** [comment]
I’ve mucked about with this locally, and should clean it up and submit a PR.

I added a function `epresent-jump-to-page` that takes a page number interactively, and a `epresent-page-number` variable that increments/decrements as you do next/prev. I use `epresent-mode-line` to display the page number on every slide. I don’t have anything to count the slides, though.

**Comment by sellout** [comment]
For the second part of this issue, the mode-line acts as the footer. In #38, I show the page number in the mode-line. As far as capturing title/author/date, I suppose those could be saved in variables when they’re fontified, and then those variables could be referenced in a custom mode-line.
