### ISSUE TITLE
org-preview-latex-fragment is obsolete since 24.4

### ISSUE THREAD

**Issue by gazzatav** [eschulte/epresent#29]
In org mode the function in the title is to be replaced with org-toggle-latex-preview for later Emacs.  At the moment I find that after running a presentation I cannot get back to the latex fragments and have to close and reopen the file.  Maybe needs a version check to decide which function to use.  C-c C-c no longer returns the file to its previous state - before running a presentation C-c C-x C-l switches the previews on and off nicely.

**Comment by sellout** [comment]
I’m confused about this issue. I’m on Emacs 25.3.2 and `org-preview-latex-fragment` exists, but `org-toggle-latex-preview` doesn’t. I also checked on Emacs 22, and neither function exists back that far.

I’m inclined to close this issue, unless @gazzatav is still interested after three years.

**Comment by gazzatav** [comment]
It should probably have been org-toggle-latex-fragment rather than -preview
and I possibly made a copy paste error or picked up a typo in my research.
After 3 years I have no clue and have no objection to the issue being
closed.
